name: Generate xml sitemap

on:
  push:
    branches: [main]

jobs:
  gen_sitemap:
    runs-on: ubuntu-latest
    name: Generate sitemap

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://bamgoesn.github.io/test-mdbook-sitemap/

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
